version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80  # O backend escuta na porta 80
    expose:
      - "80"  # Expõe a porta 80 para o Nginx
    networks:
      - backend_network

  nginx:
    image: docker.io/nginx:alpine
    container_name: nginx   
    ports:
      - "80:80"  # Apenas HTTP, removemos 443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
