version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "5000"  # Expõe a porta 5000 dentro do container para o Nginx
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend_network

  nginx:
    image: nginx:alpine  # Usando a imagem oficial do Nginx
    container_name: nginx
    ports:
      - "80:80"    # Porta 80 externa mapeada para a porta 80 do container (HTTP)
      - "443:443"  # Porta 443 externa mapeada para a porta 443 do container (HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mapeando o arquivo de configuração do Nginx
    depends_on:
      - backend  # Nginx depende do backend estar pronto
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
