version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000  # Define que o backend escute na porta correta
    expose:
      - "5000"  # Expõe a porta para a rede interna
    networks:
      - backend_network

  nginx:
    image: docker.io/nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
