version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80  # O backend agora escuta na porta 80
    expose:
      - "80"  # Expõe a porta correta para o Nginx
    networks:
      - backend_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Pasta para os certificados SSL
    depends_on:
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
